foodOrderOnline_main/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from marketplace import views as MarketplaceViews
# from rest_framework.authtoken.views import obtain_auth_token


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.home, name='home'),
    path('accounts/', include('accounts.urls')),
    # path('accounts/api-auth/', obtain_auth_token),
    path('marketplace/', include('marketplace.urls')),
    # Cart
    path('cart/', MarketplaceViews.cart, name='cart'),
    # Search
    path('search/', MarketplaceViews.search, name='search'),

    # CHEACKOUT
    path('checkout/', MarketplaceViews.checkout, name='checkout'),

    # ORDERS
    path('orders/', include('orders.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('place_order/', views.place_order, name='place_order'),
    path('payments/', views.payments, name='payments'),
    path('order_complete/', views.order_complete, name='order_complete'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.contrib.gis.db import models as gismodels
from django.contrib.gis.geos import Point



# Create your models here.
# to create BaseUserManager at first create two kinds of users. It also normalizes the email addresses
class UserManager(BaseUserManager):
    def create_user(self, first_name, last_name, username, email, password=None):
        if not email:
            raise ValueError('User must have an email address')
        if not username:
            raise ValueError('User must have an username')
        
        user = self.model(
            email = self.normalize_email(email),
            username = username,
            first_name = first_name,
            last_name = last_name,
        )
        # store a password
        user.set_password(password) 

        # self._db will take the default database that configured in settings.py
        user.save(using=self._db)
        return user
    
    def create_superuser(self, first_name, last_name, username, email, password=None):
        # assign the value to user
        user = self.create_user(
            email = self.normalize_email(email),
            username = username,
            password = password,
            first_name = first_name,
            last_name = last_name,   
        )

        # make him a superuser
        user.is_admin = True
        # user.is_active = True
        user.is_staff = True
        user.is_superadmin = True
        user.save(using=self._db)
        return user


# create a superuser
# AbstractBaseUser: by extending or inheriting this AbstractBaseUser we get full controll of editing custom user model. 
# including the authetications functionality of Django.
class User(AbstractBaseUser):
    VENDOR = 1
    CUSTOMER = 2

    ROLE_CHOICE = (
        (VENDOR, 'Vendor'),
        (CUSTOMER, 'Customer'),
    )
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=100, unique=True)
    phone_number = models.CharField(max_length=12, blank=True)
    role = models.PositiveSmallIntegerField(choices=ROLE_CHOICE, blank=True, null=True)

    #required field
    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now_add=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_superadmin = models.BooleanField(default=False)

    # AbstractBaseUser has the ability to set the user name field because by default to set the username field. Django by default uses the username
    # as login field. 
    # username itself is a required field
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']
    
    objects = UserManager()
    def __str__(self):
        return self.email
    
    def has_perm(self, perm, obj=None):
        return self.is_admin
    
    def has_module_perms(self, app_label):
        return True
    
    def get_role(self):
        if self.role == 1:
            user_role = 'Vendor'
        elif self.role == 2:
            user_role = 'Customer'
        return user_role
    

class UserProfile(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
  profile_picture = models.ImageField(upload_to='users/profile_pictures', blank=True, null=True)
  cover_photo = models.ImageField(upload_to='users/cover_photos', blank=True, null=True)
  address = models.CharField(max_length=100, blank=True, null=True)
  country = models.CharField(max_length=15, blank=True, null=True)
  state = models.CharField(max_length=15, blank=True, null=True)
  city = models.CharField(max_length=15, blank=True, null=True)
  zip_code =models.CharField(max_length=6, blank=True, null=True)
  latitude = models.CharField(max_length=20, blank=True, null=True)
  longitude = models.CharField(max_length=20, blank=True, null=True)
  location = gismodels.PointField(blank=True, null=True, srid=4326)
  created_at = models.DateTimeField(auto_now_add=True)
  modified_at = models.DateTimeField(auto_now=True)

  def __str__(self):
      return self.user.email
  
# for location based search
  def save(self, *args, **kwargs):
        # if latitude and longitude of user is available
        if self.latitude and self.longitude:
            # whenever you created point first parameter should be longitue. make the type float
            self.location = Point(float(self.longitude), float(self.latitude))
            # save it with super method
            return super(UserProfile, self).save(*args, **kwargs)
        return super(UserProfile, self).save(*args, **kwargs)
    

orders/models.py
from decimal import Decimal
import json
from django.db import models
from accounts.models import User
from menu.models import FoodItem
from vendor.models import Vendor


request_object = ''

class Payment(models.Model):
    PAYMENT_METHOD = (
        ('PayPal', 'PayPal'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    transaction_id = models.CharField(max_length=100)
    payment_method = models.CharField(choices=PAYMENT_METHOD, max_length=100)
    amount = models.CharField(max_length=10)
    status = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.transaction_id
    

class Order(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Completed', 'Completed'),
        ('Cancelled', 'Cancelled'),
    )

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)
    vendors = models.ManyToManyField(Vendor, blank=True)
    order_number = models.CharField(max_length=20)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=15, blank=True)
    email = models.EmailField(max_length=50)
    address = models.CharField(max_length=200)
    country = models.CharField(max_length=15, blank=True)
    state = models.CharField(max_length=15, blank=True)
    city = models.CharField(max_length=50)
    zip_code = models.CharField(max_length=10)
    total = models.FloatField()
    tax_data = models.JSONField(blank=True, help_text = "Data format: {'tax_type':{'tax_percentage':'tax_amount'}}", null=True)
    total_data = models.JSONField(blank=True, null=True)
    total_tax = models.FloatField()
    payment_method = models.CharField(max_length=25)
    status = models.CharField(max_length=15, choices=STATUS, default='New')
    is_ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def order_placed_to(self):
        return ", ".join([str(i) for i in self.vendors.all()])

    def __str__(self):
        return self.order_number
    
    # to get the total from each vendor
    def get_total_by_vendor(self):
        vendor = Vendor.objects.get(user=request_object.user)
        subtotal = 0
        tax = 0
 
        if self.total_data:
            print("self data I am", self.total_data)
            total_data = json.loads(self.total_data)
            print(total_data, "i am total")
            data = total_data.get(str(vendor.id), {})
            print(">>>>>",data)
            data = {str(vendor.id): data[0]} if data else {}
            print(data)

            if isinstance(data, dict):
                for key, val in data.items():
                    subtotal += float(val)
                    val = val.replace("'", '"')
                    val = json.loads(val)
                    print(subtotal)

            # if isinstance(data, list):
            # data = {str(index): value for index, value in enumerate(data)}
                
        else:
            print("Invalid data structure in total_data")
            return ValueError("Invalid data structure in total_data")
    
        grand_total = float(subtotal) + tax
        context = {
        'subtotal': subtotal,
        'grand_total': grand_total,
        }

        return context

    
  
class OrderedFood(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    fooditem = models.ForeignKey(FoodItem, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    price = models.FloatField()
    amount = models.FloatField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.fooditem.food_title

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>YumCart Food Marketplace</title>
  <!-- Google Font Family Link Start -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Montserrat:400,700">
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:400,700,800">
  <!-- Google Font Family Link End -->
 
  <!-- CSS -->
  <link href="{% static 'css/iconmoon.css' %}" rel="stylesheet"> 
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <link href="{% static 'css/custom.css' %}" rel="stylesheet"> 
  <!-- <link href="{% static 'css/style.css' %}" rel="stylesheet"> -->
 


  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <!-- JAVASCRIPT -->
  <script src="{% static 'js/custom.js' %}"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>

  <!-- Include the PayPal JavaScript SDK -->
  <script src="https://www.paypal.com/sdk/js?client-id={{PAYPAL_CLIENT_ID}}&currency=USD"></script>

  <!-- <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha256-pasqAKBDmFT4eHoN2ndd6lN370kFiGUFyTiUHWhU7k8=" crossorigin="anonymous"></script> -->
  <script src="{% static 'js/modernizr.js' %}"></script>
  <script src="{% static 'assets/js/bootstrap.js' %}"></script>
  <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
  {% if '/' == request.path or 'profile' in request.path %}
  <script src="https://maps.googleapis.com/maps/api/js?key={{GOOGLE_API_KEY}}&libraries=places&callback=initAutoComplete" async defer></script>
  {% endif %}

</head>

<body>
  

  <!-- LOAD NAVBAR HERE -->
  {% include 'includes/navbar.html' %}

  <!-- LOAD CONTENT HERE -->
  {% block content %}
  

   {% endblock%}

  <!-- LOAD FOOTER HERE -->
  {% include 'includes/footer.html' %}



  <script src="{% static 'js/app.js' %}"></script>

</body>



</html>

templates/home.html
 {% extends 'base.html' %}
 {% load static %}
 
 {% block content %}
 <!-- Main Section Start -->
 <div class="main-section box-2">
  <!-- Home Pages Elements Strat -->

  <!-- Main Search Start -->
  <div class="page-section nopadding cs-nomargin" style="padding-top: 100px; padding-bottom: 100px; margin-bottom: 0px; background: url({% static 'extra-images/bg-image1.jpg' %}) no-repeat center / cover;">
    <div class="home-container">
      <div class="cover-page-row">
          <div class="element-title-box">
            <figure class="d-flex justify-content-center">
                <img src="{% static 'logo/YumCartLogo.png' %}" alt="YumCart" width="200" height="100%">
            </figure>
            <h1 style="font-size: 40px; color: #505050; line-height: 50px; margin-bottom: 20px; text-align:center;">
              Pick Your Restaurant From <br>YumCart Food Marketplace</h1>
          </div>

          <div class="main-search fancy">
            
            <form action="{% url 'search' %}" method="GET">

                <div class="form-group">
                  <div class="field-holder">
                    <input type="text" name="keyword" placeholder="Resturant name or food name" class="search-input">
                  </div>
                </div>

                <div class="form-group">
                  <div class="field-holder foodbakery-locations-fields-group">
                        <!-- <div class="foodbakery-locations-fields-group foodbakery-focus-out"> -->
                          <span class="foodbakery-search-location-icon"><i class="icon-location"></i></span>
                          
                          <input type="text" name="address" class="location-field-text filter search-input" id="id_address" placeholder="All Locations">
                          <input type="hidden" name="lat" value="" id="id_latitude">
													<input type="hidden" name="lng" value="" id="id_longitude">
                          
                        <!-- </div> -->
                  </div>
                </div>

                <div class="form-group">
                  <div class="field-holder">
                    <select name="radius" id="radius" class="option-box" required>
                      <option value="" selected>Choose Radius</option>
                      <option value="5">5km</option>
                      <option value="10">10km</option>
                      <option value="15">15km</option>
                      <option value="25">25km</option>
                      <option value="50">50km</option>
                      <option value="75">75km</option>
                      <option value="100">100km</option>
                    </select>

                  </div>
								</div>

                <div class="search-div">
                  <div class="field-holder search-btn-div">
                    <input type="submit" value="Search">
                  </div>
                </div>

            </form>


          </div>

        
      </div>
    </div>
  </div>
  <!-- Main Search End -->
 
 <!-- Choose From Most Popular Listin Start -->
 <div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 50px;margin-bottom: 0px;background: #ffffff;">
  <div class="container">
    <div class="grid-div">
      <div class="">
        <div class="element-title align-center">
          <h2>Choose From Most Popular Restaurants</h2>
        </div>
      </div>
      <div class="">
        <div class="">
          <ul class="listing fancy">
            {% for vendor in vendors %}
            <li class="">
              <div class="list-post featured">
                <div class="img-holder">
                  <figure>
                    <a href="">
                      {% if vendor.userprofile.profile_picture %}
                      <img src="{{ vendor.userprofile.profile_picture.url }}" class="img-thumb wp-post-image" alt="">
                      {% else %}
                      <img src="{% static 'images/default-profile.png' %}" class="img-thumb wp-post-image" alt="">
                      {% endif %}
                    </a>
                  </figure>


                </div>
                <div class="text-holder">
                  
                  <div class="post-title">
                    <h5>
                      <a href="{% url 'vendor_detail' vendor.vendor_slug %}">{{ vendor }}</a>
                    </h5>
                  </div>
                  {% if vendor.userprofile.city and vendor.userprofile.state and vendor.userprofile.zip_code %}
                  <span>{{ vendor.userprofile.city }}, {{ vendor.userprofile.state }}, {{ vendor.userprofile.zip_code }}</span>
                  {% endif %}

                </div>

              </div>
            </li>
            {% endfor %}
            
  

          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Choose From Most Popular Listing End -->

  <!-- Home Pages Elements End  -->
</div>
<!-- Main Section End -->

{% endblock %}